apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-lens-config
  namespace: default
  labels:
    app.kubernetes.io/name: cluster-lens
data:
  STREAMLIT_SERVER_PORT: "8501"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"

