apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-lens
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  rules:
    - host: cluster-lens.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cluster-lens
                port:
                  number: 80

