apiVersion: v1
kind: Service
metadata:
  name: cluster-lens
  namespace: default
spec:
  selector:
    app: cluster-lens
  ports:
    - name: http
      port: 80
      targetPort: 8501
  type: NodePort
